### ISSUE TITLE
Help about how your code works

### ISSUE THREAD

**Issue by javiergarber** [Otto-AA/solid-filemanager#21]
Hello @Otto-AA , I'm a young software engineer student that is interested in see how your code works. I would like you to ask you some things. 

Maybe you are going to obviate this message but for trying I lose nothing. Well we were assigned to develop a web decentralised chat using the solid platform. The thing is that there is not that much documentation out there for us to learn to use Solid. Searching in google I found your "Solid file manager" repository and for a couple of hours I've been trying to understand how you code works and figure out how to translate it to what we need but with a really bad result. We have little JavaScript idea so even how "export" and "import" modules in js work is just a pain.

 Our application is just much much easier that yours. We actually, just want to create folders for the chat conversations and then inside the files representing the conversation itself, so we are interested in how you create,delete and update this folders or files. Would you like to suggest us  some tips or any help? For us would be like magic! 
I have to apologise myself for even writing this,and as I said you are so free to delete this and jump over, we totally understand it, it's not your problem. 
Thanks in advance so much for taking you time reading this
Regards:
Javi

**Comment by Otto-AA** [comment]
Hi Javi,

I think the part you are interested in, would be the [Api.js file](https://github.com/Otto-AA/solid-filemanager/blob/master/src/Api/Api.js), as this handles all Api calls to the solid pod (and therefore also creating folders/files). But I believe it would be easier for you to use the [solid-file-client](https://github.com/jeff-zucker/solid-file-client/), which is a simple library for " [...] creating and managing files and folders in Solid data stores", as it states on their site.

The solid-file-client is pretty straightforward to use:
First, make sure you included the library in the project (either [put the script link](https://github.com/jeff-zucker/solid-file-client/#using-in-the-browser) before your scripts in your html file, or by installing it via npm (If you don't know npm, just do first))

Then use the login method, and if the user logged in successfully you can simply use `fileClient.createFolder(url)` and stuff.

If you have more questions about the solid-file-client, please post them in their issues section

**Comment by javiergarber** [comment]
Thank you so much for you attention and help, we've been having a look at it and it seems to be quite ease to use, we'll try it soon
