### ISSUE TITLE
Reading a file fails if some predicates are not present

### ISSUE THREAD

**Issue by happybeing** [Otto-AA/solid-filemanager#23]
I filed a bug for solid-file-client which applies to your code as you also use `folderUtils.js getStats()`.

See here: https://github.com/jeff-zucker/solid-file-client/issues/30

BTW I'm finding solid-filemanager very useful for developing a fork of solid-auth-client which will work on both Solid and SAFE Network.

**Comment by Otto-AA** [comment]
Thank you for also mentioning this here, I will watch for updates in the issue. In the meantime, I've commented  `mtime` out from the stats, as my program didn't use it anyway. (Built and uploaded)

And I'm glad that the app is useful to you :)

**Comment by Otto-AA** [comment]
I've removed the unused stats, so only the size property is checked. If the size property is not available it simply hides it, so there shouldn't be errors with that from now on.
