### ISSUE TITLE
Not working in Firefox

### ISSUE THREAD

**Issue by happybeing** [Otto-AA/solid-filemanager#25]
I'm not sure if I used solid-filemanager with latest Firefox before but I just tried it and after clicking "Enter your pod" I get a popup "Error: the resource at `https://thewebalyst.solid.community/` requires you to login" and no files are displayed. The same thing in Chrome works fine.

Looking in the Firefox console I see this:
```
Source map error: request failed with status 404
Resource URL: https://otto-aa.github.io/solid-filemanager/build/static/js/main.d5cd0f84.chunk.js
Source Map URL: main.d5cd0f84.chunk.js.map[Learn More]
Source map error: request failed with status 404
Resource URL: https://otto-aa.github.io/solid-filemanager/build/static/js/2.42dfee7f.chunk.js
Source Map URL: 2.42dfee7f.chunk.js.map[Learn More]
Failed to register/update a ServiceWorker for scope ‘https://otto-aa.github.io/solid-filemanager/build/’: Load failed with status 404 for script ‘https://otto-aa.github.io/solid-filemanager/build/service-worker.js’.
Request to access cookie or storage on “https://thewebalyst.solid.community/” was blocked because we are blocking all third-party storage access requests and content blocking is enabled. build
handleFetchError main.d5cd0f84.chunk.js:1:16326
url: https://thewebalyst.solid.community/ main.d5cd0f84.chunk.js:1:16443
status: 401 main.d5cd0f84.chunk.js:1:16480
errorMessage: <!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Log in</title>
  <link rel="stylesheet" href="/common/css/bootstrap.min.css">
  <link rel="stylesheet" href="/common/css/solid.css">
</head>
<body>
<div class="container">
  <div class="page-header">
    <div class="pull-right">
      <button id="register" type="button" class="btn btn-primary">Register</button>
      <button id="login"    type="button" class="btn btn-success">Log in</button>
    </div>
    <h1>Log in to access this resource</h1>
  </div>

  <div class="alert alert-danger">
    <p>
      The resource you are trying to access
      (<code>https://thewebalyst.solid.community/</code>)
      requires you to log in.
    </p>
  </div>

</div>
</div>
<script src="/common/js/solid-auth-client.bundle.js"></script>
<script src="/common/js/auth-buttons.js"></script>
</body>
</html>
main.d5cd0f84.chunk.js:1:17148
error: [object Response] main.d5cd0f84.chunk.js:1:17190
```
In Chrome there are no messages in the browser console.

I tried disabling privacy related plugins in Firefox but didn't see any change.

**Comment by Otto-AA** [comment]
It seems that you are using an old version of solid-filemanager, I've moved it to https://otto-aa.github.io/solid-filemanager/. Can you try it with that version?

And if that doesn't fix it...
What's the version of Firefox and the pods server (4.x or 5.x)?

**Comment by happybeing** [comment]
SImilar result with https://otto-aa.github.io/solid-filemanager/.

Firefox: 66.0.2 (64-bit)
I'm not sure of NSS version or how to check that, I tried only with solid.community.

**Comment by Otto-AA** [comment]
Strange, it works for me with exactly the same version on my solid.community pod. Have you tried to logout and login again?

**Comment by happybeing** [comment]
Logging out and back in worked thanks.

Before I did that, just visiting https://otto-aa.github.io/solid-filemanager/ thought I was already logged in, but gave an error when I opened the directory saying that I was required to be logged in to access the folder. I think the Solid UX is a bit tricky!

Thanks for bearing with me. I'll try to remember to log out / log in next time I hit an issue!

**Comment by Otto-AA** [comment]
Thanks for trying it out. I will consider adding a "Have you tried to logout and login" message if I don't find the reason for this issue.
