### ISSUE TITLE
Folders are unzip as files

### ISSUE THREAD

**Issue by scenaristeur** [Otto-AA/solid-filemanager#27]
Trying to install solid-plume, with solid-filemanager, it seems that some folder are unzip as Ressource/File instead of Container/Folder as described here https://github.com/theWebalyst/solid-plume/issues/7#issuecomment-506693055
Does anyone know why? Thxs

**Comment by Otto-AA** [comment]
Can you give me some more background info? I will look into it later today or tomorrow and a detailed way to reproduce would be helpful for that:
What zip file are you using?
Have you tried it with the new version of solid-filemanager ([nightly](https://solid-filemanager.solid.community/public/nightly/)). Have you tried to completely clear the cache (updating is not finished yet, so until now you have to make a complete refresh to update. Else you may be using an old version)
What browser are you using for that (e.g. does the issue occur in Firefox)?
Could you take a look at the network requests and copy the one you think fails? If solid-filemanager tries to create an item it will make a request to the parent with `slug: my-folder-name`. So in your case I guess it is a POST request to /public/blog/plume with `slug: css`.
And what steps should I do to reproduce? Upload .zip to public/blog/, then right-cilck -> extract here? Anything else?

**Comment by georgeglessner** [comment]
Have this same issue, both on Firefox and Chrome. Using https://github.com/theWebalyst/solid-plume/archive/v0.11.zip. Tried with nightly as well and get same issue. After I upload the .zip file, I rename it to blog.zip. When I extract blog.zip, the extracted folder is renamed to the original .zip file name "solid-plume-0.11", not "blog".

**Comment by Otto-AA** [comment]
Thanks for reporting. I am currently busy myself, so don't expect a fix for it from me soon. It will likely come shortly after the release of solid-file-client v1.0.0 in September.

**Comment by Otto-AA** [comment]
@georgeglessner 
> After I upload the .zip file, I rename it to blog.zip. When I extract blog.zip, the extracted folder is renamed to the original .zip file name "solid-plume-0.11", not "blog".

I'm not sure if that is a bug though. If I'm not mistaken, the solid-plume-0.11 folder name is saved inside the zip file data, and not inferred from the zip name. So I'm not sure if or what I should change there.

Maybe create a folder named like the zip file and store everything inside? I think that would be the more common behaviour, but in your case this would still result in a blog->solid-plume-0.11->contents structure and I guess you want blog->contents. Latter won't work without changing the contents of the zip file from my point of view.

**Comment by Otto-AA** [comment]
I think this was fixed in NSS (see https://github.com/solid/node-solid-server/issues/1361).
If you still encounter this issue feel free to reopen it.
