### ISSUE TITLE
Issue logging in with Google Chrome

### ISSUE THREAD

**Issue by Leoudayan** [Otto-AA/solid-filemanager#28]
Hi,

This version works fine with Safari. But not working with google chrome. I am getting the following error message,

popup.html:24 TypeError: Cannot read property 'importKey' of undefined
    at e.value (popup.html:24)
    at Function.value (popup.html:24)
    at Function.value (popup.html:24)
    at popup.html:24
    at Array.map (<anonymous>)
    at Function.value (popup.html:24)
    at popup.html:24
et @ popup.html:24
async function (async)
et @ popup.html:24
login @ popup.html:24
(anonymous) @ popup.html:24
async function (async)
(anonymous) @ popup.html:24
E @ popup.html:24

**Comment by Otto-AA** [comment]
Which Google Chrome version do you use?
I've tried it with Version 75.0.3770.100 (Pretty much the newest) and it worked without any trouble for me. Both on the [github.io](https://otto-aa.github.io/solid-filemanager/) and the [nightly](https://solid-filemanager.solid.community/public/nightly/) version.

Also it would be useful to know if you can reproduce it with a solid.community/inrupt.net pod and at which step exactly this error occurs.

**Comment by Leoudayan** [comment]
Hi,
Thanks for the reply. I tried to login through the solid.community and inrupt. But it is giving the same error. Here is the link where i hosted your browser - http://blockchain7.kmi.open.ac.uk/solidbrowser/

Is it possible for you to check this?

**Comment by bourgeoa** [comment]
Your site is not SSL secured. It needs to be https. I connect then with no problems. Tried on android

**Comment by Leoudayan** [comment]
Ah this classical error gets me every time. Thanks for this. But i do have one more problem with all the POD logins. When i login with the root, it gives the following error. 

Error: An internal server error occured... Error translating between RDF formats

But when i try navigating to different folder, then it works. eg. /public. Any idea why its having format error?

**Comment by bourgeoa** [comment]
It is a bug in NSS V5.1.6 500 error when trying to access /(root)

**Comment by Leoudayan** [comment]
Ah okie. Thanks for the reply.

**Comment by Otto-AA** [comment]
Here is the related issue in NSS: https://github.com/solid/node-solid-server/issues/1120

And thank you @bourgeoa for your help :+1:
